# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S_01_GRC_cpp <- function(H_vec, partialH_mat, gamma_vec, X_mat, m, IndexEnterRiskSet, IndexLeaveRiskSet) {
    .Call(`_NonLinearRC_S_01_GRC_cpp`, H_vec, partialH_mat, gamma_vec, X_mat, m, IndexEnterRiskSet, IndexLeaveRiskSet)
}

